# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PQ6u6gZeRkFSggdgH0Z-n0z88svpUVPt
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv("/content/sample_data/custom_data.csv")

df.head()

df.isnull()

df.isnull().sum()

df['math_score'].fillna(df['math_score'].mean(), inplace=True)

df['placement_score'].fillna(df['placement_score'].min(), inplace=True)

df['clubing'].fillna(df['clubing'].min(), inplace=True)

df.isnull().sum()

cols = ['math_score','reading_score','writing_score','placement_score']
df[cols].boxplot()
plt.show()

np.where(df['math_score'] > 90)
np.where(df['reading_score'] < 25)
np.where(df['writing_score'] < 30)

plt.figure(figsize=(8,5))
plt.scatter(df['placement_score'], df['placement_offer'])
plt.xlabel("Placement Score")
plt.ylabel("Placement Offer")
plt.show()

np.where((df['placement_score'] < 50) & (df['placement_offer'] > 1))
np.where((df['placement_score'] > 85) & (df['placement_offer'] < 3))

from scipy import stats

z = np.abs(stats.zscore(df['math_score']))
z

